version: '3'

services:
  grafana:
    image: grafana/grafana:9.1.5
    healthcheck:
      test: wget --no-verbose --tries=1 --spider nginx1:8001
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - onelan
      - twolan

  nginx1:
    image: nginx:1.23.1
    ports:
      - "8001:8001"
    volumes:
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
    networks:
      - onelan

  nginx2:
    image: nginx:1.23.1
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8002:8002"
    networks:
      - twolan
      
networks:
  onelan:
  twolan:


